from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'project_input/', views.project_input),
    url(r'main/', views.main, name='main'),
    url(r'show_project_master/', views.show_project_master, name='show_project_master'),
    url(r'send_sample/', views.send_sample, name='send_sample'),
    url(r'^$', views.login, name='login'),
    url(r'^login/', views.login, name='login'),
    url(r'^logout/', views.logout, name='logout'),
    url(r'^search/', views.search, name='search'),
    url(r'^save_sample_info', views.save_sample_info, name='save_sample_info'),
    url(r'^down_sample_info/', views.down_sample_info, name='down_sample_info'),
    url(r'^operation_log/', views.operation_log, name='operation_log'),
    url(r'^quality_check/', views.quality_check, name='quality_check'),
    url(r'^build_lib/', views.build_lib, name='build_lib'),
    url(r'^upmachine/', views.upmachine, name='upmachine'),
    url(r'^downmachine/', views.downmachine, name='downmachine'),
    url(r'^return_sample/', views.return_sample, name='return_sample'),
    url(r'^upload_sample_info/', views.upload_sample_info, name='upload_sample_info'),
    url(r'^save_sample_row/', views.save_sample_row, name='save_sample_row'),
    url(r'^save_sample_table/', views.save_sample_table, name='save_sample_tables'),
    #url(r'^save_table_data/', views.save_table_data, name='save_table_data'),
    url(r'^upload_attachment/', views.upload_attachment, name='upload_attachment'),
    url(r'^delete_attachment/', views.delete_attachment, name='delete_attachment'),
    url(r'^show_user_detail/', views.show_user_detail, name='show_user_detail'),
    url(r'^show_expense_detail/', views.show_expense_detail, name='show_expense_detail'),
    url(r'^download_expense_info/', views.down_expense_info, name='down_expense_info'),
    url(r'^manage_billing_info/', views.manage_billing_info, name='manage_billing_info'),
    url(r'^manage_receipt_info/', views.manage_receipt_info, name='manage_receipt_info'),
    url(r'^manage_cost_info/', views.manage_cost_info, name='manage_cost_info'),
    url(r'^recover_data/', views.recover_data, name='recover_data'),
    url(r'^show_project_detail/', views.show_project_detail, name='show_project_detail'),
]
