# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-19 03:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0003_auto_20170719_0315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sampleinfodetail',
            options={'managed': True},
        ),
    ]
