# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-11 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0006_attachment_buildlib_downmachine_qualitycheck_sendsample_upmachine'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField()),
                ('project_number', models.CharField(blank=True, max_length=45, null=True)),
                ('expense', models.IntegerField(blank=True, null=True)),
                ('billing_number', models.CharField(blank=True, max_length=45, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'billing_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CostInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField()),
                ('project_number', models.CharField(blank=True, max_length=45, null=True)),
                ('expense', models.IntegerField(blank=True, null=True)),
                ('sample_number', models.CharField(blank=True, max_length=45, null=True)),
                ('unit_cost', models.CharField(blank=True, max_length=45, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'cost_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LogInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField()),
                ('action', models.CharField(blank=True, max_length=45, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('manager', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'project_log_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReceiptInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField()),
                ('project_number', models.CharField(blank=True, max_length=45, null=True)),
                ('expense', models.IntegerField(blank=True, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'receipt_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReturnSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_name', models.CharField(max_length=45)),
                ('sample_id', models.CharField(max_length=45)),
                ('location', models.CharField(max_length=100)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('upload_time', models.CharField(blank=True, max_length=100, null=True)),
                ('comment', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'return_sample',
                'managed': False,
            },
        ),
    ]
